epochs: 10                            # Number of epochs for training
test_epochs: 10                       # Number of epochs for testing
lr: 0.0001                            # Learning rate for ...
weight_decay: 0.00001                 # Weight decay for ...
