#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=Attention
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=12:00:00
#SBATCH --output=attention.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/FACT/
conda activate dl2023

pip install -r requirements.txt

python3 run.py --device cuda --dataset NBA --hMM 0.2 --hmm 0.2 --grid_search --attention
